### ISSUE TITLE
error: {build.flash_flags}: No such file or directory

### ISSUE THREAD

**Issue by thangktran** [esp8266/Arduino#5778]
I tried to integrate travis-ci into my project.
.travis.yml
```
language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-${IDE_VERSION}-linux64.tar.xz
  - tar xf arduino-${IDE_VERSION}-linux64.tar.xz
  - sudo mv arduino-${IDE_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD/libraries/aREST-master /usr/local/share/arduino/libraries/aREST-master
  - ln -s $PWD/libraries/NTPClient /usr/local/share/arduino/libraries/NTPClient
  - ln -s $PWD/libraries/AutomatedIrrigatingSystem-MegaOnly /usr/local/share/arduino/libraries/AutomatedIrrigatingSystem-MegaOnly
  - ln -s $PWD/libraries/AutomatedIrrigatingSystem-Shared /usr/local/share/arduino/libraries/AutomatedIrrigatingSystem-Shared
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - arduino --verbose --verify --board ${BOARD} ${SOURCE}
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - IDE_VERSION=1.8.8
  matrix:
    - BOARD="esp8266:esp8266:generic" SOURCE="$PWD/srcs/ESP8266/ESP8266.ino"
```

During verifying the source code, i got this error `xtensa-lx106-elf-g++: error: {build.flash_flags}: No such file or directory` and the build process exited with 1 after that.
Could this problem related to the version of Arduino IDE (1.8.8) ?
