### ISSUE TITLE
Can't use Travis CI to build ESP8266 Arduino sketches

### ISSUE THREAD

**Issue by marcoschwartz** [esp8266/Arduino#673]
Hello,

I have a bunch of projects using this library that I would like to integrate into Travis CI. However I am having an issue with the integration, I think I am doing something wrong in the configuration file. Here is the file:

```
language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266 --save-prefs
  - arduino --install-library "DHT sensor library"
script:
  - arduino --verify --board esp8266:esp8266:generic $PWD/cloud_data_logger/cloud_data_logger.ino
  - arduino --verify --board esp8266:esp8266:generic $PWD/dht_test/dht_test.ino
notifications:
  email:
    on_success: change
    on_failure: change
```

And here is part of the result on Travis CI:

```
$ arduino --install-library "DHT sensor library"
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Downloading libraries index... 
Downloading libraries index... Downloaded 0kb of 58kb.
Downloading libraries index... Downloaded 10kb of 58kb.
Downloading libraries index... Downloaded 13kb of 58kb.
Downloading libraries index... Downloaded 23kb of 58kb.
Downloading libraries index... Downloaded 33kb of 58kb.
Downloading libraries index... Downloaded 38kb of 58kb.
Downloading libraries index... Downloaded 46kb of 58kb.
Downloading libraries index... Downloaded 56kb of 58kb.
Downloading libraries index... Downloaded 58kb of 58kb.
Updating list of installed libraries
Downloading library: DHT sensor library 
Downloading library: DHT sensor library Downloaded 0kb of 4kb.
Downloading library: DHT sensor library Downloaded 2kb of 4kb.
Downloading library: DHT sensor library Downloaded 3kb of 4kb.
Downloading library: DHT sensor library Downloaded 4kb of 4kb.
Verifying archive integrity...
Installing library: DHT sensor library
Updating list of installed libraries
2.41s$ arduino --verify --board esp8266:esp8266:generic $PWD/cloud_data_logger/cloud_data_logger.ino
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
cloud_data_logger.ino:2:25: fatal error: ESP8266WiFi.h: No such file or directory
compilation terminated.
Error compiling.
The command "arduino --verify --board esp8266:esp8266:generic $PWD/cloud_data_logger/cloud_data_logger.ino" exited with 1.
```

Can anyone help? Thanks!
