### ISSUE TITLE
I cannot reset the Wi-Fi information by long pressing the button

### ISSUE THREAD

**Issue by tarontop** [esp8266/Arduino#8211]
- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP8285 device]
- Core Version:			[latest git hash or date]
- Development Env:		[Platformio]
- Operating System:		[MacOS]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

Detailed problem description goes here.

```
// Auto generated code by esphome
// ========== AUTO GENERATED INCLUDE BLOCK BEGIN ===========
#include "esphome.h"
using namespace esphome;
using namespace binary_sensor;
using namespace switch_;
logger::Logger *logger_logger;
web_server_base::WebServerBase *web_server_base_webserverbase;
captive_portal::CaptivePortal *captive_portal_captiveportal;
wifi::WiFiComponent *wifi_wificomponent;
ota::OTAComponent *ota_otacomponent;
api::APIServer *api_apiserver;
using namespace api;
web_server::WebServer *web_server_webserver;
using namespace sensor;
using namespace json;
gpio::GPIOBinarySensor *gpio_gpiobinarysensor;
binary_sensor::PressTrigger *binary_sensor_presstrigger;
Automation<> *automation;
uptime::UptimeSensor *uptime_uptimesensor;
gpio::GPIOSwitch *blue_led;
gpio::GPIOSwitch *relay;
switch_::SwitchTurnOnTrigger *switch__switchturnontrigger;
Automation<> *automation_3;
switch_::TurnOnAction<> *switch__turnonaction;
switch_::SwitchTurnOffTrigger *switch__switchturnofftrigger;
Automation<> *automation_4;
switch_::TurnOffAction<> *switch__turnoffaction;
switch_::ToggleAction<> *switch__toggleaction;
binary_sensor::ClickTrigger *binary_sensor_clicktrigger;
Automation<> *automation_2;
LambdaAction<> *lambdaaction;


// ========== AUTO GENERATED INCLUDE BLOCK END ==========="

void setup() {
  // ===== DO NOT EDIT ANYTHING BELOW THIS LINE =====
  // ========== AUTO GENERATED CODE BEGIN ===========

  App.pre_setup("plug", __DATE__ ", " __TIME__, true);
  logger_logger = new logger::Logger(115200, 512, logger::UART_SELECTION_UART0);
  logger_logger->pre_setup();
  App.register_component(logger_logger);

  web_server_base_webserverbase = new web_server_base::WebServerBase();
  App.register_component(web_server_base_webserverbase);

  captive_portal_captiveportal = new captive_portal::CaptivePortal(web_server_base_webserverbase);
  App.register_component(captive_portal_captiveportal);
  wifi_wificomponent = new wifi::WiFiComponent();
  wifi_wificomponent->set_use_address("plug.local");
  wifi::WiFiAP wifi_wifiap = wifi::WiFiAP();
  wifi_wifiap.set_ssid(test);
  wifi_wifiap.set_password("");
  wifi_wificomponent->set_ap(wifi_wifiap);
  wifi_wificomponent->set_ap_timeout(60000);
  wifi_wificomponent->set_reboot_timeout(900000);
  wifi_wificomponent->set_power_save_mode(wifi::WIFI_POWER_SAVE_NONE);
  wifi_wificomponent->set_fast_connect(false);
  wifi_wificomponent->set_output_power(20.0f);
  App.register_component(wifi_wificomponent);
  api_apiserver = new api::APIServer();
  App.register_component(api_apiserver);
  api_apiserver->set_port(6053);
  api_apiserver->set_password("");
  api_apiserver->set_reboot_timeout(900000);
  web_server_webserver = new web_server::WebServer(web_server_base_webserverbase);
  App.register_component(web_server_webserver);
  web_server_base_webserverbase->set_port(80);
  web_server_webserver->set_css_url("https://esphome.io/_static/webserver-v1.min.css");
  web_server_webserver->set_js_url("https://esphome.io/_static/webserver-v1.min.js");
  gpio_gpiobinarysensor = new gpio::GPIOBinarySensor();
  App.register_component(gpio_gpiobinarysensor);
  App.register_binary_sensor(gpio_gpiobinarysensor);
  gpio_gpiobinarysensor->set_name("Power Button");
  binary_sensor_presstrigger = new binary_sensor::PressTrigger(gpio_gpiobinarysensor);
  automation = new Automation<>(binary_sensor_presstrigger);
  uptime_uptimesensor = new uptime::UptimeSensor();
  uptime_uptimesensor->set_update_interval(60000);
  App.register_component(uptime_uptimesensor);
  App.register_sensor(uptime_uptimesensor);
  uptime_uptimesensor->set_name("Uptime Sensor");
  uptime_uptimesensor->set_unit_of_measurement("s");
  uptime_uptimesensor->set_icon("mdi:timer-outline");
  uptime_uptimesensor->set_force_update(false);
  blue_led = new gpio::GPIOSwitch();
  App.register_component(blue_led);
  App.register_switch(blue_led);
  blue_led->set_name("blue_led");
  blue_led->set_internal(true);
  blue_led->set_pin(new GPIOPin(13, OUTPUT, true));
  blue_led->set_restore_mode(gpio::GPIO_SWITCH_RESTORE_DEFAULT_OFF);
  relay = new gpio::GPIOSwitch();
  App.register_component(relay);
  App.register_switch(relay);
  relay->set_name(test);
  switch__switchturnontrigger = new switch_::SwitchTurnOnTrigger(relay);
  automation_3 = new Automation<>(switch__switchturnontrigger);
  switch__turnonaction = new switch_::TurnOnAction<>(blue_led);
  automation_3->add_actions({switch__turnonaction});
  switch__switchturnofftrigger = new switch_::SwitchTurnOffTrigger(relay);
  automation_4 = new Automation<>(switch__switchturnofftrigger);
  switch__turnoffaction = new switch_::TurnOffAction<>(blue_led);
  automation_4->add_actions({switch__turnoffaction});
  relay->set_pin(new GPIOPin(14, OUTPUT, false));
  relay->set_restore_mode(gpio::GPIO_SWITCH_RESTORE_DEFAULT_OFF);
  switch__toggleaction = new switch_::ToggleAction<>(relay);
  automation->add_actions({switch__toggleaction});
  binary_sensor_clicktrigger = new binary_sensor::ClickTrigger(gpio_gpiobinarysensor, 4000, 8000);
  automation_2 = new Automation<>(binary_sensor_clicktrigger);
  lambdaaction = new LambdaAction<>([=]() -> void {
      #line 37 "/plug.yaml"
  ESP.eraseConfig();
  delay(1000);
  ESP.reset();
  ESP.restart();
  });
  automation_2->add_actions({lambdaaction});
  gpio_gpiobinarysensor->set_pin(new GPIOPin(3, INPUT_PULLUP, true));
  // =========== AUTO GENERATED CODE END ============
  // ========= YOU CAN EDIT AFTER THIS LINE =========
  App.setup();
}

void loop() {
  App.loop();
}
```

Description of problem:
I cannot reset the Wi-Fi information by long pressing the button, it only performed a restart

Problem-relevant YAML-configuration entries:
```
esphome:
  name: plug
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285

logger:

api:

ota:

web_server:
  port: 80
  
wifi:
  ap:
    ssid: "test"
    password: ""

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    on_press:
      - switch.toggle: relay
    on_click:
      min_length: 4s
      max_length: 8s
      then:
        - lambda: |-
              ESP.eraseConfig();
              delay(1000);
              ESP.reset();
              ESP.restart();

sensor:
  - platform: uptime
    name: Uptime Sensor
    
switch:
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO13
      inverted: true

  - platform: gpio
    name: "Smart Plug"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led
```
