### ISSUE TITLE
Unexpected Relay behavior

### ISSUE THREAD

**Issue by puerto-rico** [esp8266/Arduino#8567]
From ESPHome in HomeAssistant i flashed a new firmware to discover some odd behavior on the esp.

it has been running flawsless with a 2x relay atached  for more than a year.  And that relay does not turn on a boot. default is off.
But something happend with one of the latest firmwares, not sure if is 3.2.0 but it worked 2 months ago.

What happens is that when the esp reboot's or get's powered on the relay turns on for a fraction of a sec. and then the relay closes again. this has never happends before. it is running:   espressif8266 @ 3.2.0

```

esphome:
  name: hormann

esp8266:
  board: nodemcuv2

#Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "hidden"

wifi:
  ssid: hidden
  password: hidden

switch:
  - platform: gpio
    pin: 14
    inverted: True
    id: realy
    name: "Hormann Open"
    icon: "mdi:garage-open"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: realy
  - platform: gpio
    pin: 12
    inverted: True
    id: closed
    name: "Hormann Closed"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: closed
    

```
